# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }} .

title: Pense bête
email: tarlak.desaydrone@gmail.om
description: "Un petit endroit pour me souvenir"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://desaydrone.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  "Desaydrone"

locale: "fr"

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.20.1"
minimal_mistakes_skin: "mint"

repository: "desaydrone/desaydrone.github.io"
masthead_title: "Mon pense bête"

permalink: /:title/
breadcrumbs: true

search: true

author:
  name     : "Tarlak Desaydrone"
  avatar   : "/assets/images/bio-photo.png"
  bio      : "Amateur de domotique, je partagerais des petites choses ici et la"
  location : "Somewhere France"
  links    :
      - label: "Site"
        icon: "fas fa-fw fa-link"
        url: "https://desaydrone.github.io"
      - label: "GitHub"
        icon: "fab fa-github-square"
        url: "https://github.com/desaydrone"
      - label: "Widget full Css Jeedom V4"
        icon: "fab fa-fw fa-dev"
        url: "https://github.com/Desaydrone/jeedom_v4_widget/wiki"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      author_profile: true
      layout: single
      header:
        image: /assets/images/header/chris-ried-ieic5Tq8YMk-unsplash.jpg
        caption: "Photo credit : [**Chris Ried**](https://unsplash.com/photos/ieic5Tq8YMk)"
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: true
      header:
        image: /assets/images/header/chris-ried-ieic5Tq8YMk-unsplash.jpg
        caption: "Photo credit : [**Chris Ried**](https://unsplash.com/photos/ieic5Tq8YMk)"

paginate: 10

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
